[package]
name = "cocotte"
version = "0.1.0"
authors = ["Pierre BAILLET <pierre.baillet@datadoghq.com>"]

[dependencies]

palette = "0.3.0"
config = "0.8"
clap = "2.30.0"
xdg = "2.1.0"
dirs = "1.0.4"

[[bin]]
name = "cocotte"
path = "src/cli.rs"